// react-app/src/app/custom-lion-demo.tsx
import React, { useState } from 'react';
import '@front-lab/locked-selection-list-box';
import '@lion/ui/define/lion-checkbox-group.js';
import '@lion/ui/define/lion-checkbox.js';
import '@lion/ui/define/lion-listbox.js';
import '@lion/ui/define/lion-option.js';
import { LockedSelectionListBox } from '@front-lab/locked-selection-list-box';

import './custom-lion-demo.scss';
// Web Component demo using Lion components
const CustomLionDemo = () => {
  const listboxRef = React.useRef<LockedSelectionListBox>(null);

  const [modelValue, setModelValue] =
    useState<{ resolved: boolean; selectedValue: string }[]>();

  const handleExclusiveChange = (e: CustomEvent) => {
    console.log(listboxRef?.current?.modelValue);
    setModelValue(listboxRef?.current?.modelValue || []);
  };

  return (
    <div className="container p-4">
      <h2 className="text-xl font-bold mb-6">
        Custom components extended from lion
      </h2>
      <div className="mb-6">
        <h3>locked selection list box</h3>
        {modelValue?.[0]?.selectedValue}
        <locked-selection-list-box
          ref={listboxRef}
          answer="option1"
          onmodel-value-changed={handleExclusiveChange}
        >
          <lion-option value="option1" choiceValue="option1">
            Option 1
          </lion-option>
          <lion-option value="option2" choiceValue="option2">
            Option 2
          </lion-option>
          <lion-option value="option3" choiceValue="option3">
            Option 3
          </lion-option>
          <lion-option value="option4" choiceValue="option4">
            Option 4
          </lion-option>
        </locked-selection-list-box>
      </div>
    </div>
  );
};

export default CustomLionDemo;

// angular-app/src/app/custom-lion-demo/custom-lion-demo.component.ts
import { Component, ElementRef, ViewChild, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@front-lab/locked-selection-list-box';
import '@lion/ui/define/lion-checkbox-group.js';
import '@lion/ui/define/lion-checkbox.js';
import '@lion/ui/define/lion-listbox.js';
import '@lion/ui/define/lion-option.js';
import { LockedSelectionListBox } from '@front-lab/locked-selection-list-box';

@Component({
  selector: 'app-custom-lion-demo',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './custom-lion-demo.component.html',
  styleUrls: ['./custom-lion-demo.component.scss']
})
export class CustomLionDemoComponent implements AfterViewInit {
  @ViewChild('listbox') listboxRef!: ElementRef<LockedSelectionListBox>;
  
  modelValue?: { resolved: boolean; selectedValue: string }[];

  ngAfterViewInit() {
    // Ensure the web component is properly initialized
    customElements.whenDefined('locked-selection-list-box').then(() => {
      console.log('locked-selection-list-box defined');
    });
  }

  handleExclusiveChange(e: Event) {
    const customEvent = e as CustomEvent;
    console.log(this.listboxRef?.nativeElement?.modelValue);
    this.modelValue = this.listboxRef?.nativeElement?.modelValue || [];
  }
}

<div class="container p-4">
  <h2 class="text-xl font-bold mb-6">
    Custom components extended from lion
  </h2>
  <div class="mb-6">
    <h3>locked selection list box</h3>
    <div>{{ modelValue?.[0]?.selectedValue }}</div>
    <locked-selection-list-box
      #listbox
      answer="option1"
      (model-value-changed)="handleExclusiveChange($event)"
      class="locked-listbox theme-primary"
    >
      <lion-option value="option1" choiceValue="option1" class="listbox-option">
        Option 1
      </lion-option>
      <lion-option value="option2" choiceValue="option2" class="listbox-option">
        Option 2
      </lion-option>
      <lion-option value="option3" choiceValue="option3" class="listbox-option">
        Option 3
      </lion-option>
      <lion-option value="option4" choiceValue="option4" class="listbox-option">
        Option 4
      </lion-option>
    </locked-selection-list-box>
  </div>
</div>
